grpc:
  server:
    port: 9090
    reflection-service-enabled: true

spring:
  application:
    name: cache-node

cache:
  node-id: node-1
  peers: node-2:localhost:9091,node-3:localhost:9092
  virtual-nodes: 150